### ISSUE TITLE
It's not installable by composer!

### ISSUE THREAD

**Issue by hassan-jahan** [laratalks/payment-gateways#1]
Hi Reza,

Thanks for such a great work!

The only issue is that it seems it can not be installed by composer command line.

**Comment by reshadman** [comment]
@cyberiaa NP.  I will register it on packagist  -- ASAP in my freetime -- and inform you.

**Comment by morilog** [comment]
It's now install-able by using composer:

```
composer require laratalks/payment-gateways
```
